
baseURL = 'https://viziostatic.github.io/vizio'
canonifyURLs = true

languageCode = 'en-us'
title = ' site'
theme = 'ananke'
custom_css = ["css/hugo-easy-gallery.css","css/stl.css"]

[params]
featured_image = "images/landscape.jpg"
[menu]
  [[menu.main]]
    identifier = "hugo-post"
    name = "Hugo Post"
    url = "/post"